[package]
name = "khang_first_project"
version = "0.1.0"
authors = ["khang-nghiem <31397614+khang-nghiem@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
